/* ************************************************************************
*	File: commands.h																	    Part of CircleMUD	*
*	Usage: header file for commands.c																				*
*																																					*
*	All rights reserved.  See license.doc for complete information.					*
*																																					*
*	Copyright (C) 1993, 94 by the Trustees of the Johns Hopkins University	*
* Copyright (C) 2002 by Arcane Realms MUD, created by Catherine Gore			*
*	CircleMUD is based on DikuMUD, Copyright (C) 1990, 1991.								*
************************************************************************ */

/* prototypes for all do_x functions. */
ACMD(do_action);
ACMD(do_alias);
ACMD(do_approve);
ACMD(do_assedit);
ACMD(do_assemble);
ACMD(do_assist);
ACMD(do_assminfo);
ACMD(do_astat);
ACMD(do_at);
ACMD(do_attributes);
ACMD(do_award);
ACMD(do_away);
ACMD(do_backstab);
ACMD(do_ban);
ACMD(do_bash);
ACMD(do_become);
ACMD(do_brew);
ACMD(do_buffer);
ACMD(do_calendar);
ACMD(do_cast);
ACMD(do_chase);
ACMD(do_checkdescs);
ACMD(do_chown);
ACMD(do_color);
ACMD(do_colorpref);
ACMD(do_commands);
ACMD(do_compare);
ACMD(do_consider);
ACMD(do_contact);
ACMD(do_contactinfo);
ACMD(do_copyto);
ACMD(do_cycletip);
ACMD(do_date);
ACMD(do_dc);
ACMD(do_defend);
ACMD(do_description);
ACMD(do_diagnose);
ACMD(do_dig);
ACMD(do_disarm);
ACMD(do_display);
ACMD(do_dodge);
ACMD(do_doing);
ACMD(do_drink);
ACMD(do_drop);
ACMD(do_dwield);
ACMD(do_eat);
ACMD(do_echo);
ACMD(do_edit);
ACMD(do_enable);
ACMD(do_enter);
ACMD(do_equipment);
ACMD(do_examine);
ACMD(do_exits);
ACMD(do_file);
ACMD(do_find);
ACMD(do_flee);
ACMD(do_follow);
ACMD(do_force);
ACMD(do_forge);
ACMD(do_freevnums);
ACMD(do_gecho);
ACMD(do_gen_comm);
ACMD(do_gen_door);
ACMD(do_gen_ps);
ACMD(do_gen_write);
ACMD(do_get);
ACMD(do_give);
ACMD(do_gold);
ACMD(do_goto);
ACMD(do_grab);
ACMD(do_group);
ACMD(do_gsay);
ACMD(do_hcontrol);
ACMD(do_help);
ACMD(do_helpcheck);
ACMD(do_hit);
ACMD(do_house);
ACMD(do_inventory);
ACMD(do_invis);
ACMD(do_ispell);
ACMD(do_kick);
ACMD(do_kill);
ACMD(do_languages);
ACMD(do_last);
ACMD(do_leave);
ACMD(do_lines);
ACMD(do_listskills);
ACMD(do_load);
ACMD(do_look);
ACMD(do_map);
ACMD(do_meditate);
ACMD(do_newbie);
ACMD(do_notifylist);
ACMD(do_not_here);
ACMD(do_oasis);
ACMD(do_order);
ACMD(do_overflow);
ACMD(do_page);
ACMD(do_pemote);
ACMD(do_pending);
ACMD(do_pour);
ACMD(do_practice);
ACMD(do_purge);
ACMD(do_put);
ACMD(do_qcomm);
ACMD(do_qlist);
ACMD(do_qptransfer);
ACMD(do_qstat);
ACMD(do_quit);
ACMD(do_recall);
ACMD(do_recognize);
ACMD(do_reload);
ACMD(do_remove);
ACMD(do_rename);
ACMD(do_reply);
ACMD(do_replylock);
ACMD(do_report);
ACMD(do_rescopy);
ACMD(do_rescue);
ACMD(do_rest);
ACMD(do_restore);
ACMD(do_retreat);
ACMD(do_return);
ACMD(do_rolldie);
ACMD(do_rpconvert);
ACMD(do_rplog);
ACMD(do_sac);
ACMD(do_save);
ACMD(do_say);
ACMD(do_score);
ACMD(do_scribe);
ACMD(do_send);
ACMD(do_set);
ACMD(do_show);
ACMD(do_shutdown);
ACMD(do_sit);
ACMD(do_skill_state);
ACMD(do_skills);
ACMD(do_skillset);
ACMD(do_sleep);
ACMD(do_snoop);
ACMD(do_spec_comm);
ACMD(do_split);
ACMD(do_stand);
ACMD(do_stat);
ACMD(do_switch);
ACMD(do_syslog);
ACMD(do_tedit);
ACMD(do_teleport);
ACMD(do_tell);
ACMD(do_tells);
ACMD(do_time);
ACMD(do_title);
ACMD(do_toggle);
ACMD(do_track);
ACMD(do_trans);
ACMD(do_travel);
ACMD(do_unban);
ACMD(do_undig);
ACMD(do_ungroup);
ACMD(do_use);
ACMD(do_users);
ACMD(do_wake);
ACMD(do_watch);
ACMD(do_wear);
ACMD(do_weather);
ACMD(do_where);
ACMD(do_who);
ACMD(do_whois);
ACMD(do_wield);
ACMD(do_wimpy);
ACMD(do_wipeplayer);
ACMD(do_visible);
ACMD(do_wizlock);
ACMD(do_wiznet);
ACMD(do_wizutil);
ACMD(do_vnum);
ACMD(do_world);
ACMD(do_write);
ACMD(do_vstat);
ACMD(do_xname);
ACMD(do_xsyslog);
ACMD(do_zdelete);
ACMD(do_zreset);

/* DG Script ACMD's */
ACMD(do_attach);
ACMD(do_detach);
ACMD(do_tlist);
ACMD(do_tstat);
ACMD(do_masound);
ACMD(do_mkill);
ACMD(do_mjunk);
ACMD(do_mdoor);
ACMD(do_mechoaround);
ACMD(do_msend);
ACMD(do_mecho);
ACMD(do_mload);
ACMD(do_mpurge);
ACMD(do_mgoto);
ACMD(do_mat);
ACMD(do_mteleport);
ACMD(do_mforce);
ACMD(do_mhunt);
ACMD(do_mremember);
ACMD(do_mforget);
ACMD(do_mtransform);
ACMD(do_mreward);
ACMD(do_mpet);
ACMD(do_vdelete);
ACMD(do_mdamage);
ACMD(do_mzoneecho);

/* New OLC commands */
ACMD(do_saveall);
ACMD(do_zcheck);
ACMD(do_checkloadstatus);
ACMD(do_copyover);
ACMD(do_purgemob);
ACMD(do_purgeobj);
ACMD(do_oload);
ACMD(do_slay);
ACMD(do_wlist);
ACMD(do_zone_report);
ACMD(do_mdump);
ACMD(do_odump);
ACMD(do_specset);
ACMD(do_speclist);
ACMD(do_liblist);

/* Guild System ACMDs */
ACMD(do_addguild);   
ACMD(do_remguild);   
ACMD(do_allguilds);  
ACMD(do_clubs);      
ACMD(do_myguilds);   
ACMD(do_granks);     
ACMD(do_guildinfo);  
ACMD(do_gadmininfo); 
ACMD(do_guildieinfo);
ACMD(do_guildset);   
ACMD(do_guildieset);  
ACMD(do_guild);      
ACMD(do_deguild);    
ACMD(do_seekguild);  
ACMD(do_seeking);    
ACMD(do_sponsor);    
ACMD(do_unsponsor);
ACMD(do_glist);      
ACMD(do_gdesc);      
ACMD(do_greq);       
ACMD(do_ghelp);      
ACMD(do_saveguild);  
ACMD(do_gdeposit);   
ACMD(do_gwithdraw);  
ACMD(do_gskillset);  
ACMD(do_gload);              
ACMD(do_guildwalk);
ACMD(do_gtoggle);

ACMD(do_tester);
ACMD(do_test_parse);

struct command_list_info {
	void (*command) (struct char_data *ch, char *argument, int cmd, int subcmd);
	char *name;
};

extern struct master_command_info *complete_cmd_info;
extern struct master_command_info *complete_soc_info;
extern struct command_info *cmd_info;
extern struct command_list_info command_list[];
