extern const char *AssemblyTypes[];
extern const char *AssemblyTypeNames[][3];
extern const char *AssemblyByproductLoads[];
extern const char *abbr_attributes[];
extern const char *abbr_dirs[];
extern const char *action_bits[];
extern const char *affected_bits[];
extern const char *affected_flags[];
extern const char *apply_types[];
extern const char *attributes[];
extern const char *arc_sylls[5][2][11];
extern const char *body_parts[];
extern const char *circlemud_version;
extern const char *color_liquid[];
extern const char *connected_types[];
extern const char *container_bits[];
extern const char *dirs[];
extern const char *drinks[];
extern const char *drinknames[];
extern const char *edit_modes[];
extern const char *equipment_types[];
extern const char *event_modes[];
extern const char *exit_bits[];
extern const char *extended_syslogs[];
extern const char *extra_bits[];
extern const char *fatigue_levels[];
extern const char *forage_skill[];
extern const char *forage_method[];
extern const char *fullness[];
extern const char *genders[];
extern const char *hometowns[];
extern const char *house_types[];
extern const char *item_types[];
extern const char *languages[];
extern const char *lore_methods[];
extern const char *magic_flux_types[];
extern const char *magic_routines[];
extern const char *month_name[];
extern const char *mob_difficulty_type[];
extern const char *npc_class_types[];
extern const char *npc_race_types[];
extern const char *piety_ranks[];
extern const char *position_types[];
extern const char *planes[];
extern const char *player_bits[];
extern const char *preference_bits[];
extern const char *race_size[];
extern const char *realms[];
extern const char *reputation_ranks[][2];
extern const char *resource_bits[];
extern const char *resource_groups[];
extern const char *resource_names[];
extern const char *resource_types[NUM_RESOURCE_GROUPS][NUM_RESOURCE_TYPES];
extern const char *room_bits[];
extern const char *sector_types[];
extern const char *session_toggles[];
extern const char *social_ranks[];
extern const char *spell_techniques[][3];
extern const char *spell_forms[][3];
extern const char *spell_ranges[][3];
extern const char *spell_duration[][3];
extern const char *spell_target_groups[][3];
extern const char *stredit_header;
extern const char *targets[];
extern const char *travel_defaults[];
extern const char *tutor_proficiency[];
extern const char *user_rights[];
extern const char *wear_bits[];
extern const char *weekdays[];
extern const char *wear_where[];
extern const char *wear_sort_where[];
extern const char *zone_bits[];
extern const char *zone_bits_short[];
extern const char *trig_types[];
extern const char *otrig_types[];
extern const char *wtrig_types[];
extern const struct str_app_type str_app[];
extern const struct dex_skill_type dex_app_skill[];
extern const struct dex_app_type dex_app[];
extern const struct con_app_type con_app[];
extern const struct int_app_type int_app[];
extern const struct wis_app_type wis_app[];
extern const struct log_rights log_fields[];
extern const int rev_dir[];
extern const int wear_slots[];
extern const int movement_loss[];
extern int drink_aff[][3];
extern const char *spell_seed_types[][3];
extern size_t room_bits_count;
extern size_t action_bits_count;
extern size_t affected_bits_count;
extern size_t extra_bits_count;
extern size_t wear_bits_count;
